export const suspiciousCopy = {
  conversionsTitle: "不審コンバージョン",
  countLabelConversions: "コンバージョン",
  targetDateMeta: (date: string) => `対象日: ${date}`,
  targetDateMetaPending: "利用可能な日付を待っています",
  labels: {
    search: "検索",
    searchPlaceholder: "IP、ユーザーエージェント、メディア、アフィリエイトで絞り込み",
    searchOpenButton: "検索",
    sort: "並び替え",
    riskFilter: "リスクフィルター",
    resultRange: "表示範囲",
    detail: "詳細",
    detailPanelTitle: "不審コンバージョンの詳細",
    closeDetailPanelBackdrop: "詳細パネルを閉じる",
    detailPanelRelatedTitle: "関連エンティティ",
    listFiltersLegend: "フィルター",
    tableDisplayLegend: "表示",
    groupByReasonPattern: "理由パターンでグループ化",
    groupPatternSummary: (count: number) => `${count}件がこのパターンに一致`,
    groupExpand: "グループを展開",
    groupCollapse: "グループを折りたたむ",
    backToList: "一覧に戻る",
    detailBreadcrumb: "不審コンバージョン / 詳細",
    detailEscapeHint: "Escキーで詳細パネルを閉じます。",
    all: "すべて",
    high: "高",
    medium: "中",
    low: "低",
    sortCount: "コンバージョン数（降順）",
    sortRisk: "リスク（降順）",
    sortLatest: "新しい順",
    reasons: "理由",
    relatedRows: "プログラム別内訳",
    media: "メディア",
    program: "プログラム",
    affiliate: "アフィリエイト",
    risk: "リスク",
    firstSeen: "初回検出",
    lastSeen: "最終検出",
    clickToCvGap: "クリック〜CV間隔",
    clickPadding: "クリック関連情報",
    linkedClicks: "紐づくクリック数",
    clicksPerCv: "CVあたりクリック数",
    extraWindowClicks: "ウィンドウ外クリック",
    extraWindowNonBrowserRatio: "ウィンドウ外 非ブラウザ率",
    columnIp: "IP",
    columnUserAgent: "ユーザーエージェント",
    columnUserAgentShort: "UA",
    columnReasonsShort: "理由",
    detailTableClick: "クリック",
    detailTableCv: "コンバージョン",
    score: "スコア",
    minGap: "最短",
    maxGap: "最長",
    hiddenValue: "マスク済",
    extraCount: (count: number) => `他${count}件`,
    rowActionLabel: (ip: string) => `${ip}の詳細を表示`,
  },
  pagination: {
    first: "最初",
    prev: "前へ",
    next: "次へ",
    last: "最後",
  },
  states: {
    loadingRange: "結果を読み込み中...",
    emptyRange: "一致する結果がありません",
    emptyTitle: "不審コンバージョンは見つかりませんでした",
    emptyMessage: "別の日付を選択するか、フィルター条件を緩めてください。",
    loadErrorTitle: "不審コンバージョンを読み込めませんでした",
    unauthorizedTitle: "ログインが必要です",
    unauthorizedMessage: "不審コンバージョンを閲覧するにはログインしてください。",
    forbiddenTitle: "アクセス拒否",
    forbiddenMessage: "このアカウントには不審コンバージョンへのアクセス権限がありません。",
    transientTitle: "バックエンドの一時的なエラー",
    transientMessage: "バックエンドの処理完了後にリトライしてください。",
    detailLoading: "詳細データを読み込み中...",
    detailError: "詳細データを読み込めませんでした。",
    detailForbidden: "この詳細データへのアクセス権限がありません。",
    detailUnauthorized: "この詳細データを閲覧するにはログインしてください。",
  },
} as const;

export function formatSuspiciousResultRange(start: number, end: number, total: number) {
  return `${start}〜${end} / ${total.toLocaleString("ja-JP")}件`;
}
