export const suspiciousCopy = {
  conversionsTitle: "Suspicious Conversions",
  countLabelConversions: "Conversions",
  targetDateMeta: (date: string) => `Target date: ${date}`,
  targetDateMetaPending: "Waiting for an available date",
  labels: {
    search: "Search",
    searchPlaceholder: "Filter by IP, user agent, media, or affiliate",
    searchOpenButton: "Search",
    sort: "Sort",
    riskFilter: "Risk filter",
    resultRange: "Result range",
    detail: "Details",
    detailPanelTitle: "Suspicious conversion details",
    closeDetailPanelBackdrop: "Close detail panel",
    detailPanelRelatedTitle: "Related entities",
    listFiltersLegend: "Filters",
    tableDisplayLegend: "Display",
    groupByReasonPattern: "Group rows by reason pattern",
    groupPatternSummary: (count: number) => `${count} findings share this pattern`,
    groupExpand: "Expand group",
    groupCollapse: "Collapse group",
    backToList: "Back to list",
    detailBreadcrumb: "Suspicious conversions / details",
    detailEscapeHint: "Press Esc to close the detail panel.",
    all: "All",
    high: "High",
    medium: "Medium",
    low: "Low",
    sortCount: "Conversions desc",
    sortRisk: "Risk desc",
    sortLatest: "Latest first",
    reasons: "Reasons",
    relatedRows: "Breakdown by program",
    media: "Media",
    program: "Program",
    affiliate: "Affiliate",
    risk: "Risk",
    firstSeen: "First seen",
    lastSeen: "Last seen",
    clickToCvGap: "Click-to-conversion gap",
    clickPadding: "Click context",
    linkedClicks: "Linked clicks",
    clicksPerCv: "Clicks per conversion",
    extraWindowClicks: "Extra-window clicks",
    extraWindowNonBrowserRatio: "Extra-window non-browser ratio",
    columnIp: "IP",
    columnUserAgent: "User agent",
    columnUserAgentShort: "UA",
    columnReasonsShort: "Reasons",
    detailTableClick: "Clicks",
    detailTableCv: "Conversions",
    score: "Score",
    minGap: "Min",
    maxGap: "Max",
    hiddenValue: "Masked",
    extraCount: (count: number) => `+${count} more`,
    rowActionLabel: (ip: string) => `Open details for ${ip}`,
  },
  pagination: {
    first: "First",
    prev: "Prev",
    next: "Next",
    last: "Last",
  },
  states: {
    loadingRange: "Loading results...",
    emptyRange: "No matching rows",
    emptyTitle: "No suspicious conversions found",
    emptyMessage: "Try another date or relax the current filters.",
    loadErrorTitle: "Could not load suspicious conversions",
    unauthorizedTitle: "Login required",
    unauthorizedMessage: "You need to sign in before viewing suspicious conversions.",
    forbiddenTitle: "Access denied",
    forbiddenMessage: "Your account does not have access to suspicious conversions.",
    transientTitle: "Temporary backend issue",
    transientMessage: "Retry after the backend finishes processing.",
    detailLoading: "Loading detail data...",
    detailError: "Could not load detail data.",
    detailForbidden: "You do not have access to this detail payload.",
    detailUnauthorized: "Sign in to view this detail payload.",
  },
} as const;

export function formatSuspiciousResultRange(start: number, end: number, total: number) {
  return `${start}-${end} of ${total.toLocaleString("en-US")}`;
}
