from __future__ import annotations


JP_TEST_NAME_MAP = {
    "test_health_requires_admin_token": "管理者トークンなしのヘルスチェックは拒否される",
    "test_ingest_clicks_rejects_invalid_date": "クリック取り込みは不正な日付入力を拒否する",
    "test_refresh_returns_conflict_when_job_is_running": "更新ジョブ実行中の再実行要求は競合エラーになる",
    "test_suspicious_clicks_returns_business_friendly_fields": "疑わしいクリックAPIは業務向け項目を返す",
    "test_suspicious_conversions_rejects_invalid_date": "疑わしい成果APIは不正日付入力を拒否する",
    "test_format_reasons_and_risk_scoring_reflect_business_priority": "判定理由整形とリスクスコアは業務優先度を反映する",
    "test_root_returns_running_message": "ルートAPIは稼働中メッセージを返す",
    "test_refresh_accepts_request_when_job_can_be_enqueued": "更新APIはジョブ受付可能時に受理を返す",
    "test_summary_endpoint_returns_payload": "サマリーAPIは集計結果を返す",
    "test_daily_stats_endpoint_returns_data": "日次統計APIは時系列データを返す",
    "test_suspicious_clicks_returns_empty_when_latest_date_is_missing": "疑わしいクリックAPIは対象日未登録時に空結果を返す",
    "test_dates_endpoint_returns_available_dates": "利用可能日付APIは日付一覧を返す",
    "test_job_status_endpoint_maps_store_status": "ジョブ状態APIは実行中状態を返す",
    "test_job_status_endpoint_returns_completed_payload": "ジョブ状態APIは完了結果を返す",
    "test_job_status_endpoint_returns_failed_payload": "ジョブ状態APIは失敗結果を返す",
    "test_health_returns_warning_when_data_is_missing": "ヘルスチェックはデータ不足時に警告を返す",
    "test_settings_endpoints_use_service_layer": "設定APIは設定サービスの結果を返す",
    "test_sync_masters_enqueues_background_job": "マスタ同期APIはバックグラウンドジョブを登録する",
    "test_masters_status_returns_repository_stats": "マスタ状態APIはリポジトリ統計を返す",
    "test_extract_bearer_parses_authorization_header": "Bearer認証ヘッダからトークンを抽出できる",
    "test_require_admin_allows_dev_mode_without_admin_key": "開発環境では管理鍵未設定でも管理認可を許可する",
    "test_require_admin_raises_in_production_without_admin_key": "本番環境で管理鍵未設定の場合はサーバーエラーになる",
    "test_filter_findings_matches_media_name_when_include_names_enabled": "検索フィルタは媒体名でも疑わしい結果を絞り込める",
    "test_format_dt_serializes_datetime_and_string": "日時整形はdatetimeと文字列を正しく返す",
    "test_run_refresh_collects_detect_results_per_date": "更新ジョブは日付ごとの検知件数を集計する",
    "test_run_refresh_without_detect_does_not_add_detect_key": "検知無効の更新ジョブ結果には検知キーを含めない",
    "test_enqueue_job_raises_conflict_when_another_job_is_running": "ジョブ実行中に新規登録すると競合例外になる",
    "test_enqueue_job_persists_failure_when_runner_raises": "ジョブ実行失敗時は失敗状態が保存される",
    "test_enqueue_job_completes_when_runner_succeeds": "ジョブ実行成功時は完了状態が保存される",
    "test_run_click_ingestion_returns_summary_message": "クリック取り込みジョブは件数付きメッセージを返す",
    "test_run_conversion_ingestion_returns_summary_message": "成果取り込みジョブは件数付きメッセージを返す",
    "test_run_master_sync_returns_upsert_counts": "マスタ同期ジョブは更新件数を返す",
    "test_click_run_for_date_clears_target_date_when_no_clicks": "クリック日次取り込みはデータなし時に対象日をクリアする",
    "test_click_run_for_date_paginates_and_ingests": "クリック日次取り込みはページングして保存する",
    "test_click_run_for_time_range_filters_and_merges": "クリック時間範囲取り込みは期間外を除外してマージする",
    "test_conversion_run_for_date_counts_valid_entries_and_ingests": "成果日次取り込みは有効エントリー数を集計して保存する",
    "test_conversion_run_for_time_range_filters_and_returns_counts": "成果時間範囲取り込みは期間外除外と件数返却を行う",
    "test_get_settings_merges_env_defaults_and_db_overrides": "設定取得は環境初期値にDB上書きを適用する",
    "test_get_settings_uses_cache_after_first_load": "設定取得は初回読込後にキャッシュを利用する",
    "test_update_settings_returns_persisted_true_when_save_succeeds": "設定保存成功時は永続化済みフラグを返す",
    "test_update_settings_returns_warning_when_save_fails": "設定保存失敗時は警告付きで設定値を返す",
    "test_resolve_acs_settings_parses_token_and_normalizes_values": "ACS設定解決はトークン分解と値正規化を行う",
    "test_resolve_acs_settings_rejects_insecure_url_by_default": "ACS設定解決はデフォルトで非HTTPS URLを拒否する",
    "test_resolve_acs_settings_requires_positive_page_size": "ACS設定解決は正のページサイズのみ許可する",
    "test_resolve_rules_reads_env_and_overrides_explicit": "クリック検知ルール解決は明示値で環境値を上書きする",
    "test_resolve_conversion_rules_uses_explicit_values": "成果検知ルール解決は明示値を優先する",
    "test_build_rule_sets_uses_settings": "ルールセット構築は設定値を正しく反映する",
    "test_run_refresh_includes_detect": "更新ジョブで検知有効時に検知結果が含まれる",
    "test_get_latest_date_rejects_unsupported_table": "最新日付取得は未対応テーブルを拒否する",
    "test_get_latest_date_returns_none_when_table_has_no_rows": "最新日付取得はデータなし時にNoneを返す",
    "test_get_latest_date_converts_date_object_to_iso": "最新日付取得は日付オブジェクトをISO文字列で返す",
    "test_resolve_summary_date_chooses_latest_across_click_and_conversion": "サマリー対象日解決はクリックと成果の最新日を比較する",
    "test_resolve_summary_date_falls_back_to_yesterday": "サマリー対象日解決はデータなし時に前日を採用する",
    "test_get_summary_returns_business_facing_totals": "サマリー集計は業務向け合計値を返す",
    "test_get_daily_stats_merges_click_and_conversion_rows": "日次統計はクリックと成果を日付単位で統合する",
    "test_get_available_dates_returns_unique_descending": "利用可能日付取得は重複除去して降順で返す",
    "test_get_summary_handles_datetime_style_resolved_date": "サマリー集計は日時形式の対象日でも処理できる",
    "test_get_daily_stats_skips_invalid_date_rows": "日次統計は不正日付行を検知件数計算から除外する",
    "test_conversion_burst_threshold_is_used": "成果バースト判定は設定した閾値を使用する",
    "test_postgres_smoke": "PostgreSQL接続と基本クエリが成功する",
    "test_click_detector_applies_threshold_and_burst_reason": "クリック検知は閾値超過とバースト理由を付与する",
    "test_conversion_detector_adds_gap_only_findings": "成果検知は時間差異常のみでも不正候補を追加する",
    "test_conversion_detector_respects_browser_and_datacenter_filters": "成果検知はブラウザ限定とデータセンター除外を適用する",
    "test_combined_detector_marks_intersection_as_high_risk": "統合検知はクリックと成果の重複端末を高リスクにする",
    "test_click_detector_adds_media_and_program_reasons": "クリック検知は媒体数と案件数の理由を付与する",
    "test_conversion_detector_adds_max_gap_reason": "成果検知は最大経過秒超過の理由を付与する",
    "test_fetch_click_logs_returns_click_models_and_auth_header": "クリックログ取得は認証付きでモデルへ変換する",
    "test_fetch_click_logs_raises_http_error_when_status_is_not_200": "クリックログ取得はAPI異常時にHTTPエラーを送出する",
    "test_fetch_conversion_logs_maps_entry_fields": "成果ログ取得はエントリー情報を含めて変換する",
    "test_fetch_click_logs_for_time_range_uses_date_bounds": "クリック時間範囲取得は開始日と終了日を検索条件に使う",
    "test_fetch_conversion_logs_for_time_range_uses_date_bounds": "成果時間範囲取得は開始日と終了日を検索条件に使う",
    "test_fetch_master_endpoints_map_records": "マスタ取得APIは媒体案件ユーザーの項目を整形する",
    "test_fetch_all_master_methods_iterate_pages_until_short_page": "全件マスタ取得は最終ページまでページングする",
    "test_normalize_query_converts_positional_parameters": "SQL正規化は位置パラメータを名前付きへ変換する",
    "test_normalize_query_raises_when_placeholder_count_mismatches": "SQL正規化はプレースホルダ数不一致で例外を返す",
    "test_fetch_click_to_conversion_gaps_returns_empty_when_table_missing": "成果経過秒集計はテーブル未作成時に空結果を返す",
    "test_fetch_click_to_conversion_gaps_aggregates_min_max_and_count": "成果経過秒集計は最小最大件数を端末単位で集計する",
    "test_enrich_conversions_with_click_info_matches_by_cid": "成果とクリックの突合はcid一致データのみ返す",
    "test_get_all_masters_returns_counts_and_last_synced": "マスタ統計取得は件数と最終同期日時を返す",
    "test_load_settings_parses_json_and_keeps_plain_text": "設定読込はJSON値を復元し文字列はそのまま保持する",
    "test_timezone_name_uses_default_when_env_is_missing": "タイムゾーン名取得は環境変数未設定時に既定値を使う",
    "test_timezone_name_trims_whitespace": "タイムゾーン名取得は前後の空白を除去する",
    "test_get_timezone_falls_back_to_utc_when_resolution_fails": "タイムゾーン解決失敗時はUTCへフォールバックする",
    "test_now_local_returns_naive_datetime": "現在時刻取得はタイムゾーンなし日時を返す",
    "test_parse_datetime_keeps_naive_datetime_as_is": "日時解析はナイーブdatetimeをそのまま返す",
    "test_parse_datetime_converts_aware_datetime_to_local_naive": "日時解析はタイムゾーン付きdatetimeをローカル時刻へ変換する",
    "test_parse_datetime_handles_epoch_seconds_and_milliseconds": "日時解析は秒とミリ秒のepoch値を解釈する",
    "test_parse_datetime_handles_iso_and_plain_format_strings": "日時解析はISO形式と通常形式文字列を解釈する",
    "test_parse_datetime_returns_now_for_invalid_or_empty_values": "日時解析は不正値と空値で現在時刻を返す",
    "test_parse_numeric_and_normalize_epoch_cover_edge_cases": "数値解析とepoch正規化は境界条件を処理する",
    "test_today_local_uses_configured_timezone": "今日の日付取得は設定タイムゾーンを反映する",
    "test_normalize_database_url_converts_postgres_prefixes": "DB接続URL正規化はpostgres接頭辞をpsycopg形式へ変換する",
    "test_get_database_url_raises_when_env_is_missing": "DB接続URL取得は環境変数未設定時に例外を返す",
    "test_get_database_url_returns_normalized_env_value": "DB接続URL取得は環境値を正規化して返す",
    "test_get_engine_uses_explicit_url": "DBエンジン生成は明示URLを優先する",
    "test_get_sessionmaker_binds_engine": "セッションメーカー生成はエンジンをバインドする",
    "test_ensure_schema_creates_table_and_inserts_singleton_row": "ジョブ状態スキーマ初期化は単一行を作成する",
    "test_get_returns_default_idle_when_row_is_missing": "ジョブ状態取得は未登録時に初期アイドル状態を返す",
    "test_get_parses_json_result_when_row_exists": "ジョブ状態取得はJSON結果を辞書へ復元する",
    "test_start_returns_true_when_update_succeeds": "ジョブ開始は更新成功時にTrueを返す",
    "test_start_returns_false_when_update_does_not_change_rows": "ジョブ開始は更新失敗時にFalseを返す",
    "test_complete_and_fail_delegate_to_finish": "ジョブ完了と失敗は共通終了処理へ委譲する",
    "test_finish_serializes_result_and_executes_update": "ジョブ終了処理は結果JSONを保存して状態更新する",
    "test_browser_filter_sql_contains_includes_and_excludes": "ブラウザUAフィルタSQLは包含条件と除外条件を含む",
    "test_datacenter_filter_sql_returns_empty_for_no_prefixes": "データセンターIPフィルタSQLは接頭辞なしで空文字を返す",
    "test_count_raw_rows_returns_zero_when_raw_table_does_not_exist": "生クリック件数取得はテーブル未作成時に0を返す",
    "test_count_raw_rows_returns_scalar_count": "生クリック件数取得は集計件数を返す",
    "test_fetch_rollups_maps_rows_to_models": "クリック集計取得はロールアップモデルへ変換する",
    "test_fetch_suspicious_rollups_applies_filters_and_maps_rows": "疑わしいクリック取得はフィルタSQLを適用してモデル化する",
    "test_fetch_suspicious_conversion_rollups_returns_empty_when_table_missing": "疑わしい成果取得はテーブル未作成時に空を返す",
    "test_lookup_clicks_methods_cover_missing_and_found_paths": "クリックID参照は単体取得と複数取得の両方を処理する",
    "test_get_existing_ids_return_sets": "既存ID取得はクリックと成果で集合を返す",
    "test_get_suspicious_detail_bulk_methods_map_rows": "疑わしい詳細一括取得は媒体名案件名を補完して返す",
    "test_save_settings_returns_without_execute_when_empty": "設定保存は入力が空の場合に書き込みを行わない",
    "test_require_database_url_raises_when_missing": "CLIはDB接続URL未設定時に処理を中断する",
    "test_build_parser_accepts_refresh_and_sync_masters": "CLIパーサーは更新コマンドとマスタ同期コマンドを受け付ける",
    "test_cmd_refresh_rejects_conflicting_flags": "CLI更新コマンドは排他的オプションの同時指定を拒否する",
    "test_cmd_refresh_runs_ingestion_and_detection": "CLI更新コマンドは取り込みと不正検知を実行する",
    "test_cmd_refresh_conversions_only_skips_click_warning": "CLI更新コマンドの成果のみ実行ではクリック警告を表示しない",
    "test_cmd_sync_masters_updates_all_master_types": "CLIマスタ同期は媒体案件ユーザーをすべて更新する",
    "test_main_prints_help_and_returns_1_for_unknown_command": "CLIメインはコマンド未指定時にヘルプを表示して終了コード1を返す",
}


def pytest_collection_modifyitems(items):
    for item in items:
        original_name = getattr(item, "originalname", item.name)
        jp_name = JP_TEST_NAME_MAP.get(original_name)
        if not jp_name:
            continue
        item.name = jp_name
        base_nodeid = item.nodeid.rsplit("::", 1)[0]
        item._nodeid = f"{base_nodeid}::{jp_name}"
