from __future__ import annotations

from datetime import date, datetime
from typing import Protocol


class ReportingRepository(Protocol):
    database_url: str

    def fetch_one(self, query, params=None): ...
    def fetch_all(self, query, params=None): ...
    def get_click_ipua_coverage(self, target_date: date): ...
    def get_conversion_click_enrichment(self, target_date: date): ...
    def get_all_masters(self): ...
    def get_settings_updated_at(self): ...
    def get_latest_settings_version_id(self): ...
    def get_conversion_data_watermark(self, target_date: date): ...
    def get_conversion_findings_lineage(self, target_date: date): ...
    def count_current_conversion_findings(self, target_date: date) -> int: ...
    def get_daily_finding_counts(
        self,
        limit: int,
        *,
        target_date: date | None = None,
    ) -> dict[str, dict[str, int]]: ...


class FindingsRepository(Protocol):
    def get_settings_updated_at(self): ...
    def ensure_settings_version(self, settings: dict, fingerprint: str) -> str: ...
    def get_click_data_watermark(self, target_date: date): ...
    def get_conversion_data_watermark(self, target_date: date): ...
    def fetch_conversion_click_padding_metrics(
        self,
        target_date: date,
        ip_ua_pairs: list[tuple[str, str]],
        *,
        extra_window_seconds: int,
    ): ...
    def get_suspicious_conversion_details_bulk(
        self, target_date: date, pairs: list[tuple[str, str]]
    ): ...
    def get_program_unit_prices(self, target_date: date, program_ids: list[str]): ...
    def replace_conversion_findings(
        self, target_date: date, rows: list[dict], *, generation_metadata: dict
    ) -> None: ...


class FindingsReadRepository(Protocol):
    def get_suspicious_conversion_details_bulk(
        self, target_date: date, pairs: list[tuple[str, str]]
    ): ...
    def list_conversion_findings(
        self,
        *,
        target_date: date,
        limit: int,
        offset: int,
        search: str | None,
        risk_level: str | None,
        sort_by: str,
        sort_order: str,
    ) -> tuple[list[dict], int]: ...
    def get_conversion_finding_by_key(self, finding_key: str) -> dict | None: ...


class FindingsWriteRepository(Protocol):
    def replace_conversion_findings(
        self, target_date: date, rows: list[dict], *, generation_metadata: dict
    ) -> None: ...


class SettingsRepository(Protocol):
    def load_settings(self) -> dict: ...
    def save_settings(self, settings: dict, *, fingerprint: str) -> str | None: ...
    def ensure_settings_version(self, settings: dict, fingerprint: str) -> str: ...
    def get_settings_updated_at(self): ...
    def get_latest_settings_version_id(self): ...


class LifecycleRepository(Protocol):
    def purge_raw_before(self, cutoff: datetime, *, execute: bool) -> dict[str, int]: ...
    def purge_aggregates_before(self, cutoff: date, *, execute: bool) -> dict[str, int]: ...
    def purge_findings_before(self, cutoff: date, *, execute: bool) -> dict[str, int]: ...
