export const fraudCopy = {
  title: "不正判定",
  targetDateMeta: (date: string) => `対象日: ${date}`,
  targetDateMetaPending: "対象日を選択してください",
  labels: {
    search: "検索",
    searchPlaceholder: "アフィリエイト、メディア、プログラム、理由で検索",
    resultRange: "表示範囲",
    detailHint: "行を選択すると詳細を表示できます。",
    detail: "詳細",
    detailPlaceholder: "行を選択すると詳細を表示します。",
    detailPanelTitle: "選択中の不正判定",
    closeDetail: "詳細を閉じる",
    user: "アフィリエイト",
    media: "メディア",
    promotion: "プログラム",
    reasons: "理由",
    details: "判定指標",
    metric: "件数",
    risk: "リスク",
    retry: "再試行",
    firstDetected: "初回検知",
    lastDetected: "最終検知",
    detailsEmpty: "表示できる判定指標はありません。",
  },
  columns: {
    metric: "件数",
    user: "アフィリエイト",
    media: "メディア",
    promotion: "プログラム",
    risk: "リスク",
    reasons: "理由",
    detail: "詳細",
  },
  states: {
    loadingRange: "不正判定を読み込み中...",
    emptyRange: "表示できる不正判定はありません",
    emptyTitle: "不正判定はありません",
    emptyMessage: "対象日と現在の条件に一致する不正判定はありません。",
    loadErrorTitle: "不正判定を読み込めませんでした",
    loadErrorMessage: "不正判定を読み込めませんでした。",
    datesErrorMessage: "利用可能な日付を読み込めませんでした。",
    unauthorizedTitle: "ログインが必要です",
    unauthorizedMessage: "不正判定を閲覧するにはログインしてください。",
    forbiddenTitle: "アクセス拒否",
    forbiddenMessage: "このリソースへのアクセス権限がありません。",
    transientTitle: "一時的なエラー",
    transientMessage: "バックエンドの復旧後に再試行してください。",
    detailError: "選択した詳細を読み込めませんでした。",
  },
  formatResultRange(start: number, end: number, total: number) {
    return `${start}〜${end} / ${total.toLocaleString("ja-JP")}件`;
  },
} as const;
