export const fraudCopy = {
  title: "Fraud Findings",
  targetDateMeta: (date: string) => `Target date: ${date}`,
  targetDateMetaPending: "Select a target date",
  labels: {
    search: "Search",
    searchPlaceholder: "Search by affiliate, media, promotion, or reason",
    resultRange: "Visible range",
    detail: "Details",
    detailPlaceholder: "Select a row to inspect its details.",
    user: "Affiliate",
    media: "Media",
    promotion: "Promotion",
    reasons: "Reasons",
    details: "Detail payload",
    metric: "Count",
    risk: "Risk",
    retry: "Retry",
  },
  columns: {
    metric: "Count",
    user: "Affiliate",
    media: "Media",
    promotion: "Promotion",
    risk: "Risk",
    reasons: "Reasons",
    detail: "Details",
  },
  states: {
    loadingRange: "Loading findings...",
    emptyRange: "No findings available",
    emptyTitle: "No fraud findings",
    emptyMessage: "No findings matched the current date and filters.",
    loadErrorTitle: "Could not load fraud findings",
    loadErrorMessage: "Could not load fraud findings.",
    datesErrorMessage: "Could not load available dates.",
    unauthorizedTitle: "Login required",
    unauthorizedMessage: "You need to sign in to view fraud findings.",
    forbiddenTitle: "Access denied",
    forbiddenMessage: "You do not have access to this resource.",
    transientTitle: "Temporary error",
    transientMessage: "Please retry after the backend recovers.",
    detailError: "Could not load the selected detail.",
  },
  formatResultRange(start: number, end: number, total: number) {
    return `${start}-${end} / ${total.toLocaleString("ja-JP")}`;
  },
} as const;
