export const suspiciousCopy = {
  clicksTitle: "不審クリック",
  conversionsTitle: "不審コンバージョン",
  countLabelClicks: "クリック数",
  countLabelConversions: "CV数",
  labels: {
    targetDate: "対象日",
    search: "一覧を検索",
    searchPlaceholder: "IP / User-Agent / 媒体 / 案件",
    sort: "並び順",
    detail: "詳細",
    close: "閉じる",
    all: "すべて",
    high: "高",
    medium: "中",
    low: "低",
    sortCount: "件数順",
    sortRisk: "リスク順",
    sortLatest: "最新順",
    masked: "一覧ではマスク表示",
    reasons: "検知理由",
    evidence: "証跡状態",
    relatedRows: "関連行",
    summary: "概要",
    media: "媒体",
    program: "案件",
    affiliate: "アフィリエイター",
    risk: "リスク",
    firstSeen: "初回検知",
    lastSeen: "最終検知",
    clickToCvGap: "Click→CV 時間差",
  },
  states: {
    loadingRange: "読み込み中...",
    emptyRange: "対象データなし",
    emptyTitle: "該当する finding はありません",
    emptyMessage: "条件を変えると検知結果が見つかる場合があります。",
    loadErrorTitle: "一覧の取得に失敗しました",
    unauthorizedTitle: "認証が必要です",
    unauthorizedMessage: "一覧を表示するには read access が必要です。",
    forbiddenTitle: "表示権限がありません",
    forbiddenMessage: "この一覧を表示する権限がありません。",
    transientTitle: "一時的な取得エラー",
    transientMessage: "しばらく待ってから再読込してください。",
    detailLoading: "詳細を読み込み中です...",
    detailError: "詳細の取得に失敗しました。",
    evidenceExpired:
      "証跡保持期間を過ぎているため、この finding は一覧のみ表示しています。",
    evidenceAvailable:
      "証跡は保持期間内です。詳細の関連行と元データを確認できます。",
    evidenceUnknown: "証跡状態を判定できませんでした。",
    staleHint:
      "一覧は表示できますが、最新の再計算ではない可能性があります。",
    maskedHint:
      "一覧では機微情報をマスクしています。詳細な値は詳細画面でのみ確認できます。",
    detailForbidden: "この詳細を表示する権限がありません。",
    detailUnauthorized: "詳細を表示するには認証が必要です。",
  },
} as const;
